name: A Blog
author: Yesufu
url: https://lightfish-zhang.github.io
resume_site: https://lightfish-zhang.github.io
baseurl: 
description: you website desc
github_username: lightfish-zhang
github: https://github.com/lightfish-zhang
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : xxx
    clientSecret : xxx
    repo : lightfish-zhang.github.io
    owner : lightfish-zhang
    admin : lightfish-zhang

---
layout: post
title: A Example Post
date:   1970-01-01 00:00:00 +0800
category: tutorial
thumbnail: /style/image/thumbnail.jpg
icon: book
---


* content
{:toc}

## sub title

page...

## about thumbnail

add the thumbnail url

## about icon

such as book, code, web, chat, note, game, link, design, image
